#!/usr/bin/env node
// Populate public/vendor/ (gitignored) from the pins: the browser bundles the
// /admin page uses from the pinned npm packages, and the offline TTS engine
// from the pinned wasmtts release tarball. Runs automatically before
// `pnpm run dev` and `pnpm run deploy`, so the served assets always match
// package.json — Renovate bumps a version, the next deploy ships it.

import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { ensureEngine, packEntries, pinnedTag, readAssets, root, runtimeScripts, sha256 } from "./wasmtts-pin.mjs";

const outDir = join(root, "public", "vendor");

const BUNDLES = [
  // simplified→traditional only (1.0MB); the full bi-directional bundle is not needed
  { pkg: "opencc-js", src: "dist/esm/cn2t.js", dst: "opencc-cn2t.js" },
  { pkg: "fflate", src: "esm/browser.js", dst: "fflate.js" },
  // The JS applier for sherpa's rule FSTs — the node tests' oracle for the
  // real kaldifst wasm (scripts/test-matcha-fst.mjs), from the wasmtts git
  // tree: never served to a page, so it lives beside the bundles, not under
  // wasmtts/ (everything there rides the service worker shell).
  { pkg: "wasmtts", src: "platform/matcha-fst.js", dst: "matcha-fst.js" },
];

// The engine files the tarball ships that the reader serves same-origin under
// /vendor/wasmtts/ (all ride the service worker shell — test-shell-policy.mjs
// derives the list from the same names). NOT the compiled lexicon: 2.3 MB
// under a content-hashed packName is a pack file, served by /api/wasmtts from
// the assets release and cached by the synth worker like a model.
export const ENGINE_FILES = [
  "matcha-engine.js", "matcha-worker.js", "matcha-producer.mjs", "continuous-stream-player.mjs",
  "matcha-frontend.js", "matcha-taiwan-profile.js", "matcha-synthesis.js", "kaldifst-normalizer.js",
  "matcha-kaldifst-normalizer.js", "matcha-kaldifst-normalizer.wasm",
  "matcha-profile.runtime.json", "matcha-assets.json", "matcha-lexicon.meta.json",
];

mkdirSync(outDir, { recursive: true });
mkdirSync(join(outDir, "wasmtts"), { recursive: true });
const versions = {};
for (const { pkg, src, dst } of BUNDLES) {
  const pkgDir = join(root, "node_modules", pkg);
  copyFileSync(join(pkgDir, src), join(outDir, dst));
  versions[pkg] = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")).version;
}

// The Matcha engine, whole, from the pinned release tarball (verified against
// the release's .sha256 in wasmtts-pin.mjs) — upstream runs the release gates
// (FST golden, RTF, memory, ASR CER, the streaming player) this repo cannot,
// and the tarball is the only place the compiled lexicon, the runtime profile
// and the complete pack manifest exist.
const tag = pinnedTag();
const engine = await ensureEngine(tag);
const assets = readAssets(engine);
for (const f of ENGINE_FILES) copyFileSync(join(engine, f), join(outDir, "wasmtts", f));
versions.wasmtts = tag;

// The runtime scripts (ort's UMD + loader glue, lamejs) come from the npm
// packages the wasmtts dependency itself resolves — the versions upstream's
// gates tested — under the versioned packNames the pack manifest's runtime
// block declares, and every byte is checked against its sha256 there: a pin
// whose lockfile resolved a different build than its manifest names fails
// here, not on a phone.
const runtime = runtimeScripts(assets);
for (const r of runtime) {
  const installed = JSON.parse(readFileSync(join(r.dir, "package.json"), "utf8"));
  if (installed.version !== r.version)
    throw new Error(`${r.pkg} ${installed.version} is installed but the wasmtts pin's runtime block names ${r.version}`);
  const bytes = readFileSync(r.local);
  if (bytes.length !== r.bytes || sha256(bytes) !== r.sha256)
    throw new Error(`${r.pkg}/${r.file}: installed bytes do not match the pin's runtime block (${r.name})`);
  writeFileSync(join(outDir, "wasmtts", r.name), bytes);
  versions[r.pkg] = r.version;
}

// The pack manifest for the reader and the worker: the complete assets
// definition (the pin's own words, no name written here) and the flat list
// of release-served names /api/wasmtts may answer for. wasm-tts.mjs builds
// the synth worker's config from ASSETS; src/worker.js allowlists PACK_NAMES;
// sync-wasmtts-assets.mjs keeps the release in step with the same list.
const entries = packEntries(assets, engine);
const packNames = entries.map((e) => e.name);
writeFileSync(join(outDir, "wasmtts", "pack-manifest.mjs"),
  `// generated by scripts/vendor.mjs from ${tag}'s matcha-assets.json — do not edit\n`
  + `export const ASSETS = ${JSON.stringify(assets)};\n`
  + `export const PACK_NAMES = ${JSON.stringify(packNames)};\n`
  + `export const WASMTTS_TAG = ${JSON.stringify(tag)};\n`);
writeFileSync(join(outDir, "versions.json"), JSON.stringify(versions, null, 2) + "\n");

// Drop anything this run did not produce. CI deploys from a fresh checkout, so
// public/vendor/ there holds exactly what is listed above; a long-lived
// working copy otherwise keeps serving files from pins that moved months ago,
// and a stale bundle that only exists locally is how "works on my machine"
// starts. Pruning makes the two match.
const keep = new Set([
  ...BUNDLES.map(({ dst }) => dst),
  ...ENGINE_FILES.map((f) => `wasmtts/${f}`),
  ...runtime.map((r) => `wasmtts/${r.name}`),
  "versions.json", "wasmtts/pack-manifest.mjs",
]);
const stale = [];
const walk = (dir) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, e.name);
    if (e.isDirectory()) walk(abs);
    else if (!keep.has(relative(outDir, abs))) { rmSync(abs); stale.push(relative(outDir, abs)); }
  }
};
walk(outDir);

const mb = (n) => (n / 1048576).toFixed(1);
console.log(`✓ vendored to public/vendor/: ${Object.entries(versions).map(([p, v]) => `${p}@${v}`).join(", ")}`);
console.log(`  engine ${tag}: ${ENGINE_FILES.length} files, runtime ${runtime.map((r) => r.name).join(", ")}, pack ${packNames.length} names (${mb(entries.reduce((s, e) => s + e.bytes, 0))} MiB)`);
if (stale.length) console.log(`  pruned ${stale.length} stale file(s): ${stale.join(", ")}`);
